name: Deploy

on:
  push:
    branches: ["release"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.200

      - name: Install .NET Wasm Tools
        run: dotnet workload install wasm-tools

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Publish .NET
        run: dotnet publish Multa.Web/Multa.Web.csproj -c:Release --nologo -p:StaticWebAssetBasePath=Multa

      - name: Verificar estrutura da pasta publish
        run: ls -R Multa.Web/bin/Release/

      - name: Replace base href for GitHub Pages
        run: sed -i 's|<base href="/"|<base href="/Multa/"|' Multa.Web/bin/Release/net9.0/publish/wwwroot/Multa/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true

      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'Multa.Web/bin/Release/net9.0/publish/wwwroot/Multa'

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
