name: Deploy

on:
  push:
    branches: ["release"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.200

      - name: Install .NET Wasm Tools
        run: dotnet workload install wasm-tools

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Publish .NET
        run: dotnet publish Multa.Web/Multa.Web.csproj -c:Release -o docs --nologo -p:StaticWebAssetBasePath=Multa

      - name: Move contents from wwwroot to root
        run: |
          mv docs/wwwroot/* docs/
          rm -rf docs/wwwroot

      - name: Move Multa contents to root (caso estejam dentro de /Multa)
        run: |
          if [ -d "docs/Multa" ]; then
            mv docs/Multa/* docs/
            rm -rf docs/Multa
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true

      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
